docker:
  image: yegor256/rultor-image
  as_root: true
assets:
  settings.xml: "portlek/secret-repo#configs/settings.xml"
  pubring.gpg: "portlek/secret-repo#configs/pubring.gpg"
  secring.gpg: "portlek/secret-repo#configs/secring.gpg"
architect:
  - portlek
merge:
  script: |
    mvn clean install --errors --settings ../settings.xml
deploy:
  script: |
    export GPG_TTY=$(tty)
    mvn clean deploy --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" --settings ../settings.xml
    git commit -am "${tag}"
    export GPG_TTY=$(tty)
    mvn clean deploy --errors --settings ../settings.xml
