docker:
  image: yegor256/rultor
assets:
  settings.xml: "portlek/secret-repo#configs/settings.xml"
  pubring.gpg: "portlek/secret-repo#configs/pubring.gpg"
  secring.gpg: "portlek/secret-repo#configs/secring.gpg"
architect:
  - portlek
merge:
  script: |
    mvn clean install --errors --settings /home/r/settings.xml -ntp
deploy:
  script: |
    mvn clean deploy --errors --settings /home/r/settings.xml -ntp
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml -ntp
    git commit -am "${tag}"
    mvn clean deploy --errors --settings /home/r/settings.xml -ntp
