language: java
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
